CREATE TABLE T_CUSTOMER_TYPE (
	ID INT PRIMARY KEY,
	CUSTOMER_TYPE VARCHAR(30) NOT NULL
)

CREATE TABLE T_CUSTOMER_SITUATION(
	ID INT PRIMARY KEY,
	CUSTOMER_SITUATION VARCHAR(20) NOT NULL
)

CREATE TABLE T_CUSTOMER(
	ID INT PRIMARY KEY,
	NAME VARCHAR(200) NOT NULL,
	CPF	VARCHAR(12) NOT NULL,
	CUSTOMER_TYPE	VARCHAR(30) NOT NULL,
	GENDER	VARCHAR(20) NOT NULL,
	CUSTOMER_SITUATION VARCHAR(20) NOT NULL	
)